import { BaselinePanel } from "@/components/BaselinePanel";
import { ModeMatrixCard } from "@/components/ModeMatrixCard";
import { SellerResponseModeCard } from "@/components/SellerResponseModeCard";

/**
 * Settings page — Iteration 6 home for the mode matrix, plus the iter-5
 * baseline panel (operator-facing system health). WEDGE1 / M1 adds the
 * SellerResponseModeCard between mode matrix and baseline.
 *
 * Other settings pages can be added here later (notification prefs, agent
 * config exports, etc).
 */
export function Settings() {
  return (
    <div className="space-y-6">
      <div className="glass-card p-5">
        <h2 className="font-semibold text-lg">Settings</h2>
        <p className="text-sm text-muted-foreground">
          System posture and baseline. Trust mode and seller response mode are set at agent startup via env vars
          (CREDENTIAL_MODE, SIGNING_MODE, SELLER_RESPONSE_MODE) — edit <code>A2A/js/.env</code> and restart the
          buyer + seller agents. Baseline is regenerated by{" "}
          <code>npm run replay:fixtures</code> in <code>A2A/js</code>.
        </p>
      </div>

      <ModeMatrixCard />
      <SellerResponseModeCard />
      <BaselinePanel />
    </div>
  );
}
